version: '3.8'

services:
  db:
    image: postgres:15
    container_name: getout-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - getout-net

  backend:
    build:
      context: ./backend
    container_name: getout-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - getout-net

  frontend:
    build:
      context: ./frontend
    container_name: getout-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - getout-net

volumes:
  pg_data:

networks:
  getout-net:
    driver: bridge

